feat(api) add missing step to registration workflow
mlco2/codecarbon pull request #616
Opened 2024-07-21 15:34 UTC by prmths128

Note: needs a fix to organization registration to work. There's an exception there.

2024-07-22 15:11 UTC, inimaz requested changes

2024-07-22 15:18 UTC, prmths128 commented on carbonserver/carbonserver/api/services/signup_service.py
> +                new_user = self._user_repository.create_user(
Ah, yes !
I just noticed that too with a DB error

2024-07-22 15:18 UTC, prmths128 commented on carbonserver/carbonserver/api/services/signup_service.py
> +                new_user = self._user_repository.create_user(
fixed

2024-07-23 06:52 UTC, inimaz approved these changes
Looks good! Thanks as well for the fix on the `subscribe_user_to_org` method

2024-07-23 07:29 UTC, SaboniAmine approved these changes
That's great! Will it be possible to deploy this, in a near future ? This might help front end integration :-)

2024-07-23 07:56 UTC, merged