Log tracking method used and required installs for tracking CPU
mlco2/codecarbon pull request #641
Opened 2024-08-20 22:41 UTC by rosekelly6400

Addresses Issue #585 

- moved the code that sets the ram, cpu and gpu tracking into its own function
- added additional logging saying what RAM, CPU and GPU tracking methods are being used and logging giving instructions on what needs to be installed to improve tracking accuracy

2024-08-27 14:58 UTC, rosekelly6400 commented
@benoit-cty @inimaz this pull request is for addressing issue [#585: Log steps to install needed codecarbon dependencies ](https://github.com/mlco2/codecarbon/issues/585) Is this what you were looking for? Happy to make more changes if needed

2024-09-01 11:24 UTC, benoit-cty requested changes
Thanks a lot !
You need to add `import sys` to `util.py`.

2024-09-01 11:24 UTC, benoit-cty commented on codecarbon/emissions_tracker.py
> +                cpu_tracking_install_instructions = "Mac OS and ARM processor detected: Please enable PowerMetrics sudo to measure CPU"
```suggestion
                    cpu_tracking_install_instructions = "Mac OS and ARM processor detected: Please enable PowerMetrics sudo to measure CPU"
```

2024-09-01 11:24 UTC, benoit-cty commented on codecarbon/emissions_tracker.py
> +            # PRINT WHAT TO INSTALL TO INCREASE ACCURACY
```suggestion
            # Explain what to install to increase accuracy
```

2024-09-04 03:23 UTC, rosekelly6400 commented
> Thanks a lot ! You need to add `import sys` to `util.py`.

@benoit-cty all the requested changes have been added and pushed

2024-09-04 19:58 UTC, rosekelly6400 commented
@benoit-cty sorry was having some issues running the hatch scripts locally to test the pipelines but got them working now, hopefully the pipeline should pass now

2024-09-08 08:23 UTC, benoit-cty approved these changes

2024-09-08 08:25 UTC, benoit-cty commented
Thanks, your contribution will be in the 2.7.0 that I will release today.

2024-09-08 08:25 UTC, merged