Updating the docs and adding Comet integration
mlco2/codecarbon pull request #68
Opened 2020-11-19 16:41 UTC by sashavor

I fixed some URL issues in the docs and added the Comet integration details from the README

2020-11-19 16:48 UTC, vict0rsch commented
LTGM

@nikolaskaris is going to update the comet assets to display in the readme so maybe we should wait for those before merging the update to the docs

2020-11-19 16:48 UTC, vict0rsch commented
Failed tests are fixed in #63

2020-11-20 18:38 UTC, kngoyal requested changes

2020-11-20 18:38 UTC, kngoyal commented on docs/_sources/comet.rst.txt
> +.. image:: ./images/comet-workspace.png
@sashavor can you move the `.png` files in `docs/_images` to `docs/edit/images` for that is the path you are referring to here, which will get populated eventually in `docs/_images` as Sphinx will make those renderings on its own.

2020-11-20 19:44 UTC, kngoyal approved these changes

2020-11-20 20:20 UTC, merged